---
- name: restart celery
  service: name=celery state=restarted enabled=yes

- name: restart celerybeat
  service: name=celerybeat state=restarted enabled=yes

- name: restart gunicorn
  service: name=osm-export-tool2 state=restarted enabled=yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload postfix
  service: name=postfix state=reloaded enabled=yes

#- name: restart apache2
#  service: name=apache2 state=restarted enabled=yes

#- name: restart overpassapi
#  service: name=overpassapi state=restarted enabled=yes
